[tool.poetry]
name = "testaction"
version = "0.1.0"
description = ""
authors = ["Simone Biffi <simone.biffi.91@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
